version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    links:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
